# Generated by Django 4.0.6 on 2022-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvmodel',
            old_name='fname',
            new_name='studentName',
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='personalPhoto',
            field=models.ImageField(default=None, upload_to='imgfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='studentaddress',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='studentcat',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='studentdob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='studentemail',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='studentgender',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='studentpnumber',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
