# Generated by Django 4.0.6 on 2022-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cvmodel_signaturephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmodel',
            name='image',
        ),
    ]
