# Generated by Django 4.0.6 on 2022-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='minimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('personalPhoto', models.ImageField(default='imagesfolder', upload_to='')),
            ],
        ),
    ]
